name: Build and deploy container app to Azure Web App - store-portal-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t mcr.microsoft.com/store-template:${{ github.sha }} -f ./store.api/Dockerfile .
      
      - name: Push Docker image to MCR
        run: docker push mcr.microsoft.com/store-template:${{ github.sha }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Login to Docker Registry
        uses: docker/login-action@v3
        with:
          registry: mcr.microsoft.com
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E8AD3434E7A4B7B9713E0875E7FD1F5 }}  
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_BF95B056655A459E9B9B0017C64F5117 }} 

      - name: Deploy to Azure Web App (via App Service)
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'store-portal-back' 
          slot-name: 'production'  
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AE83A0784854416089A13AEF97857EA0 }}  
          images: 'mcr.microsoft.com/store-template:${{ github.sha }}'  
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E8AD3434E7A4B7B9713E0875E7FD1F5 }}  
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_BF95B056655A459E9B9B0017C64F5117 }} 
