name: Build and deploy container app to Azure Web App - store-portal-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - uses: actions/checkout@v2

      # Set up .NET
      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0' # Substitua pela versão do .NET usada no seu projeto

      # Restore dependencies for both projects
      - name: Restore dependencies
        run: dotnet restore ./store.api/store.api.csproj && dotnet restore ./store.test/store.test.csproj

      # Run unit tests from the tests project
      - name: Run unit tests
        run: dotnet test ./store.test/store.test.csproj --no-restore --verbosity normal

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: storeportal.azurecr.io
          username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E8AD3434E7A4B7B9713E0875E7FD1F5 }}
          password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_BF95B056655A459E9B9B0017C64F5117 }}

  # Restore dependencies for both projects
      - name: Restore dependencies
        run: dotnet restore ./store.api/store.api.csproj && dotnet restore ./store.test/store.test.csproj

      # Run unit tests from the tests project
      - name: Run unit tests
        run: dotnet test ./store.test/store.test.csproj --no-restore --verbosity normal

      # Build and push Docker image to ACR
      - name: Build and push Docker image
        run: |
          docker build -t storeportal.azurecr.io/store-template:${{ github.sha }} -f ./store.api/Dockerfile .
          docker push storeportal.azurecr.io/store-template:${{ github.sha }}

      # Deploy to Azure App Service
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'store-portal-back'  # Nome do App Service
          images: 'storeportal.azurecr.io/store-template:${{ github.sha }}'  # Imagem no ACR
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_AE83A0784854416089A13AEF97857EA0 }}
