name: Build and deploy container app to Azure Web App - store-portal-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t store-portal-back:${{ github.sha }} -f ./store.api/Dockerfile .

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Login to Docker Registry
      uses: docker/login-action@v2
      with:
        registry: mcr.microsoft.com
        username: mandrade
        password: Teste@123  # Armazene a senha no GitHub Secrets

    - name: Deploy to Azure Web App (via App Service)
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'store-portal-back'  # Nome do seu App Service
        slot-name: 'production'  # O slot de produção ou outro slot de implantação
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Usando o publish profile
        images: 'mcr.microsoft.com/store-template:${{ github.sha }}'  # Nome da imagem no Docker Registry
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME }}  # Nome de usuário do App Service
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD }}  # Senha do App Service
