name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 6.0.x
    - name: List files in the current directory
      run: ls -al  
    - name: Restore dependencies
      run: dotnet restore store.api/store.api.sln 
    - name: Build
      run: dotnet build store.api/store.api.sln --no-restore  
    - name: Test
      run: dotnet test store.test/store.test.csproj --no-build --verbosity normal  
    - name: Publish Test Results
      if: success() || failure()
      run: |
        mkdir -p $(System.DefaultWorkingDirectory)/TestResults
        dotnet test store.test/store.test.csproj --no-build --logger "trx;LogFileName=test_results.trx"
        mv test_results.trx $(System.DefaultWorkingDirectory)/TestResults/test_results.trx
    - name: Upload Test Results to GitHub
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: $(System.DefaultWorkingDirectory)/TestResults/test_results.trx
