name: Build and deploy container app to Azure Web App - store-portal-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t store-portal-back:${{ github.sha }} -f ./store.api/Dockerfile .

    - name: Build and push container image to Azure Web App
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: store-portal-back:${{ github.sha }}  # Use o nome correto para a imagem
        file: ./store.api/Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'store-portal-back'
        slot-name: 'production'
        publish-url: 'store-portal-back-f9fcd9gsdxhxd3f2.scm.brazilsouth-01.azurewebsites.net:443'  
        username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME_8E8AD3434E7A4B7B9713E0875E7FD1F5 }}  
        password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD_BF95B056655A459E9B9B0017C64F5117 }}  #
        images: 'store-portal-back:${{ github.sha }}'  
