name: Build and deploy container app to Azure Web App - store-portal-back

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t store-portal-back:${{ github.sha }} .

   # - name: Log in to Azure Container Registry (Optional)
    #  uses: docker/login-action@v2
     # with:
      #  registry: storeportalapp.azurecr.io  # Se você estiver usando ACR, caso contrário remova esta etapa
       # username: ${{ secrets.AZUREAPPSERVICE_CONTAINERUSERNAME }}
        #password: ${{ secrets.AZUREAPPSERVICE_CONTAINERPASSWORD }}

    - name: Build and push container image to Azure Web App
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: store-portal-back:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'store-portal-back'
        slot-name: 'production'
        publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}  # Use seu publish-profile aqui
        images: 'store-portal-back:${{ github.sha }}'
